# Generated by Django 4.2.7 on 2024-01-14 13:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOODGIT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_create',
            field=models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
