# Generated by Django 5.0.1 on 2024-01-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GOODGIT', '0002_profile_date_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_create',
        ),
    ]
