# Generated by Django 5.0.1 on 2024-03-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GOODGIT', '0005_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='author',
            new_name='user',
        ),
    ]
